// Comprehensive Swiss postal codes database covering all 26 cantons
export interface PostalCodeEntry {
  code: string;
  city: string;
  canton: string;
}

export const swissPostalCodes: PostalCodeEntry[] = [
  // Zürich (ZH) - Comprehensive coverage
  { code: "8000", city: "Zürich", canton: "ZH" },
  { code: "8001", city: "Zürich", canton: "ZH" },
  { code: "8002", city: "Zürich", canton: "ZH" },
  { code: "8003", city: "Zürich", canton: "ZH" },
  { code: "8004", city: "Zürich", canton: "ZH" },
  { code: "8005", city: "Zürich", canton: "ZH" },
  { code: "8006", city: "Zürich", canton: "ZH" },
  { code: "8008", city: "Zürich", canton: "ZH" },
  { code: "8032", city: "Zürich", canton: "ZH" },
  { code: "8037", city: "Zürich", canton: "ZH" },
  { code: "8038", city: "Zürich", canton: "ZH" },
  { code: "8044", city: "Zürich", canton: "ZH" },
  { code: "8045", city: "Zürich", canton: "ZH" },
  { code: "8046", city: "Zürich", canton: "ZH" },
  { code: "8047", city: "Zürich", canton: "ZH" },
  { code: "8048", city: "Zürich", canton: "ZH" },
  { code: "8049", city: "Zürich", canton: "ZH" },
  { code: "8050", city: "Zürich Oerlikon", canton: "ZH" },
  { code: "8051", city: "Zürich", canton: "ZH" },
  { code: "8052", city: "Zürich", canton: "ZH" },
  { code: "8053", city: "Zürich", canton: "ZH" },
  { code: "8055", city: "Zürich", canton: "ZH" },
  { code: "8057", city: "Zürich", canton: "ZH" },
  { code: "8063", city: "Zürich", canton: "ZH" },
  { code: "8064", city: "Zürich", canton: "ZH" },
  { code: "8102", city: "Oberengstringen", canton: "ZH" },
  { code: "8103", city: "Unterengstringen", canton: "ZH" },
  { code: "8104", city: "Weiningen", canton: "ZH" },
  { code: "8105", city: "Regensdorf", canton: "ZH" },
  { code: "8106", city: "Adlikon", canton: "ZH" },
  { code: "8107", city: "Buchs", canton: "ZH" },
  { code: "8108", city: "Dällikon", canton: "ZH" },
  { code: "8109", city: "Kloster Fahr", canton: "ZH" },
  { code: "8112", city: "Otelfingen", canton: "ZH" },
  { code: "8113", city: "Boppelsen", canton: "ZH" },
  { code: "8114", city: "Dänikon", canton: "ZH" },
  { code: "8115", city: "Hüttikon", canton: "ZH" },
  { code: "8117", city: "Fällanden", canton: "ZH" },
  { code: "8118", city: "Pfaffhausen", canton: "ZH" },
  { code: "8121", city: "Benglen", canton: "ZH" },
  { code: "8122", city: "Binz", canton: "ZH" },
  { code: "8123", city: "Ebmatingen", canton: "ZH" },
  { code: "8124", city: "Maur", canton: "ZH" },
  { code: "8125", city: "Zollikerberg", canton: "ZH" },
  { code: "8126", city: "Zumikon", canton: "ZH" },
  { code: "8127", city: "Forch", canton: "ZH" },
  { code: "8132", city: "Egg", canton: "ZH" },
  { code: "8133", city: "Esslingen", canton: "ZH" },
  { code: "8134", city: "Adliswil", canton: "ZH" },
  { code: "8135", city: "Langnau am Albis", canton: "ZH" },
  { code: "8136", city: "Gattikon", canton: "ZH" },
  { code: "8142", city: "Uitikon Waldegg", canton: "ZH" },
  { code: "8143", city: "Stallikon", canton: "ZH" },
  { code: "8152", city: "Glattbrugg", canton: "ZH" },
  { code: "8153", city: "Rümlang", canton: "ZH" },
  { code: "8154", city: "Oberglatt", canton: "ZH" },
  { code: "8155", city: "Niederhasli", canton: "ZH" },
  { code: "8157", city: "Dielsdorf", canton: "ZH" },
  { code: "8162", city: "Steinmaur", canton: "ZH" },
  { code: "8180", city: "Bülach", canton: "ZH" },
  { code: "8181", city: "Höri", canton: "ZH" },
  { code: "8182", city: "Hochfelden", canton: "ZH" },
  { code: "8184", city: "Bachenbülach", canton: "ZH" },
  { code: "8185", city: "Winkel", canton: "ZH" },
  { code: "8186", city: "Neerach", canton: "ZH" },
  { code: "8187", city: "Weiach", canton: "ZH" },
  { code: "8193", city: "Eglisau", canton: "ZH" },
  { code: "8197", city: "Rafz", canton: "ZH" },
  { code: "8302", city: "Kloten", canton: "ZH" },
  { code: "8303", city: "Bassersdorf", canton: "ZH" },
  { code: "8304", city: "Wallisellen", canton: "ZH" },
  { code: "8305", city: "Dietlikon", canton: "ZH" },
  { code: "8306", city: "Brüttisellen", canton: "ZH" },
  { code: "8307", city: "Effretikon", canton: "ZH" },
  { code: "8308", city: "Illnau", canton: "ZH" },
  { code: "8309", city: "Nürensdorf", canton: "ZH" },
  { code: "8310", city: "Grafstal", canton: "ZH" },
  { code: "8400", city: "Winterthur", canton: "ZH" },
  { code: "8401", city: "Winterthur", canton: "ZH" },
  { code: "8404", city: "Winterthur", canton: "ZH" },
  { code: "8405", city: "Winterthur", canton: "ZH" },
  { code: "8406", city: "Winterthur", canton: "ZH" },
  { code: "8408", city: "Winterthur", canton: "ZH" },
  { code: "8409", city: "Winterthur", canton: "ZH" },
  { code: "8412", city: "Aesch-Neftenbach", canton: "ZH" },
  { code: "8413", city: "Neftenbach", canton: "ZH" },
  { code: "8414", city: "Buch am Irchel", canton: "ZH" },
  { code: "8415", city: "Berg am Irchel", canton: "ZH" },
  { code: "8418", city: "Schlatt", canton: "ZH" },
  { code: "8421", city: "Dättlikon", canton: "ZH" },
  { code: "8422", city: "Pfungen", canton: "ZH" },
  { code: "8424", city: "Embrach", canton: "ZH" },
  { code: "8425", city: "Oberembrach", canton: "ZH" },
  { code: "8427", city: "Rorbas", canton: "ZH" },
  { code: "8428", city: "Teufen", canton: "ZH" },
  { code: "8451", city: "Kleinandelfingen", canton: "ZH" },
  { code: "8452", city: "Adlikon", canton: "ZH" },
  { code: "8460", city: "Marthalen", canton: "ZH" },
  { code: "8461", city: "Oerlingen", canton: "ZH" },
  { code: "8462", city: "Rheinau", canton: "ZH" },
  { code: "8463", city: "Benken", canton: "ZH" },
  { code: "8465", city: "Wildensbuch", canton: "ZH" },
  { code: "8466", city: "Trüllikon", canton: "ZH" },
  { code: "8467", city: "Truttikon", canton: "ZH" },
  { code: "8468", city: "Guntalingen", canton: "ZH" },
  { code: "8471", city: "Rutschwil (Dägerlen)", canton: "ZH" },
  { code: "8472", city: "Seuzach", canton: "ZH" },
  { code: "8474", city: "Dinhard", canton: "ZH" },
  { code: "8475", city: "Ossingen", canton: "ZH" },
  { code: "8476", city: "Unterstammheim", canton: "ZH" },
  { code: "8477", city: "Oberstammheim", canton: "ZH" },
  { code: "8478", city: "Thalheim an der Thur", canton: "ZH" },
  { code: "8479", city: "Altikon", canton: "ZH" },
  { code: "8484", city: "Weisslingen", canton: "ZH" },
  { code: "8486", city: "Rikon im Tösstal", canton: "ZH" },
  { code: "8487", city: "Rämismühle", canton: "ZH" },
  { code: "8488", city: "Turbenthal", canton: "ZH" },
  { code: "8489", city: "Schalchen", canton: "ZH" },
  { code: "8492", city: "Wila", canton: "ZH" },
  { code: "8493", city: "Saland", canton: "ZH" },
  { code: "8494", city: "Bauma", canton: "ZH" },
  { code: "8495", city: "Schmidrüti", canton: "ZH" },
  { code: "8496", city: "Steg im Tösstal", canton: "ZH" },
  { code: "8497", city: "Fischenthal", canton: "ZH" },
  { code: "8498", city: "Gibswil", canton: "ZH" },
  { code: "8500", city: "Frauenfeld", canton: "TG" },
  { code: "8501", city: "Frauenfeld", canton: "TG" },
  { code: "8502", city: "Frauenfeld", canton: "TG" },
  { code: "8536", city: "Hüttwilen", canton: "TG" },
  { code: "8542", city: "Wiesendangen", canton: "ZH" },
  { code: "8543", city: "Gundetswil", canton: "ZH" },
  { code: "8544", city: "Attikon", canton: "ZH" },
  { code: "8545", city: "Rickenbach", canton: "ZH" },
  { code: "8546", city: "Kefikon", canton: "ZH" },
  { code: "8547", city: "Gachnang", canton: "TG" },
  { code: "8600", city: "Dübendorf", canton: "ZH" },
  { code: "8601", city: "Dübendorf", canton: "ZH" },
  { code: "8602", city: "Wangen-Brüttisellen", canton: "ZH" },
  { code: "8603", city: "Schwerzenbach", canton: "ZH" },
  { code: "8604", city: "Volketswil", canton: "ZH" },
  { code: "8605", city: "Gutenswil", canton: "ZH" },
  { code: "8606", city: "Greifensee", canton: "ZH" },
  { code: "8607", city: "Aathal-Seegräben", canton: "ZH" },
  { code: "8608", city: "Bubikon", canton: "ZH" },
  { code: "8610", city: "Uster", canton: "ZH" },
  { code: "8611", city: "Uster", canton: "ZH" },
  { code: "8614", city: "Bertschikon", canton: "ZH" },
  { code: "8615", city: "Wermatswil", canton: "ZH" },
  { code: "8616", city: "Riedikon", canton: "ZH" },
  { code: "8617", city: "Mönchaltorf", canton: "ZH" },
  { code: "8618", city: "Oetwil am See", canton: "ZH" },
  { code: "8620", city: "Wetzikon", canton: "ZH" },
  { code: "8621", city: "Wetzikon", canton: "ZH" },
  { code: "8623", city: "Wetzikon", canton: "ZH" },
  { code: "8624", city: "Grüt", canton: "ZH" },
  { code: "8625", city: "Gossau", canton: "ZH" },
  { code: "8626", city: "Ottikon", canton: "ZH" },
  { code: "8630", city: "Rüti", canton: "ZH" },
  { code: "8632", city: "Tann", canton: "ZH" },
  { code: "8633", city: "Wolfhausen", canton: "ZH" },
  { code: "8634", city: "Hombrechtikon", canton: "ZH" },
  { code: "8635", city: "Dürnten", canton: "ZH" },
  { code: "8636", city: "Wald", canton: "ZH" },
  { code: "8637", city: "Laupen", canton: "ZH" },
  { code: "8638", city: "Goldingen", canton: "SG" },
  { code: "8700", city: "Küsnacht", canton: "ZH" },
  { code: "8702", city: "Zollikon", canton: "ZH" },
  { code: "8703", city: "Erlenbach", canton: "ZH" },
  { code: "8704", city: "Herrliberg", canton: "ZH" },
  { code: "8707", city: "Uetikon am See", canton: "ZH" },
  { code: "8708", city: "Männedorf", canton: "ZH" },
  { code: "8712", city: "Stäfa", canton: "ZH" },
  { code: "8713", city: "Uerikon", canton: "ZH" },
  { code: "8714", city: "Feldbach", canton: "ZH" },
  { code: "8715", city: "Bollingen", canton: "SG" },
  { code: "8716", city: "Schmerikon", canton: "SG" },
  { code: "8717", city: "Benken", canton: "SG" },
  { code: "8718", city: "Schänis", canton: "SG" },
  { code: "8722", city: "Kaltbrunn", canton: "SG" },
  { code: "8723", city: "Rufi", canton: "SG" },
  { code: "8725", city: "Ernetschwil", canton: "SG" },
  { code: "8726", city: "Ricken", canton: "SG" },
  { code: "8730", city: "Uznach", canton: "SG" },
  { code: "8732", city: "Neuhaus", canton: "SG" },
  { code: "8733", city: "Eschenbach", canton: "SG" },
  { code: "8734", city: "Ermenswil", canton: "SG" },
  { code: "8735", city: "St. Gallenkappel", canton: "SG" },
  { code: "8750", city: "Glarus", canton: "GL" },
  { code: "8751", city: "Urnäsch", canton: "AR" },
  { code: "8752", city: "Näfels", canton: "GL" },
  { code: "8753", city: "Mollis", canton: "GL" },
  { code: "8754", city: "Netstal", canton: "GL" },
  { code: "8755", city: "Ennenda", canton: "GL" },
  { code: "8756", city: "Mitlödi", canton: "GL" },
  { code: "8757", city: "Filzbach", canton: "GL" },
  { code: "8758", city: "Obstalden", canton: "GL" },
  { code: "8762", city: "Schwändi", canton: "GL" },
  { code: "8767", city: "Elm", canton: "GL" },
  { code: "8800", city: "Thalwil", canton: "ZH" },
  { code: "8802", city: "Kilchberg", canton: "ZH" },
  { code: "8803", city: "Rüschlikon", canton: "ZH" },
  { code: "8804", city: "Au", canton: "ZH" },
  { code: "8805", city: "Richterswil", canton: "ZH" },
  { code: "8806", city: "Bäch", canton: "SZ" },
  { code: "8807", city: "Freienbach", canton: "SZ" },
  { code: "8808", city: "Pfäffikon", canton: "SZ" },
  { code: "8810", city: "Horgen", canton: "ZH" },
  { code: "8815", city: "Horgenberg", canton: "ZH" },
  { code: "8816", city: "Hirzel", canton: "ZH" },
  { code: "8820", city: "Wädenswil", canton: "ZH" },
  { code: "8824", city: "Schönenberg", canton: "ZH" },
  { code: "8825", city: "Hütten", canton: "ZH" },
  { code: "8832", city: "Wollerau", canton: "SZ" },
  { code: "8834", city: "Schindellegi", canton: "SZ" },
  { code: "8835", city: "Feusisberg", canton: "SZ" },
  { code: "8840", city: "Einsiedeln", canton: "SZ" },
  { code: "8841", city: "Gross", canton: "SZ" },
  { code: "8842", city: "Unteriberg", canton: "SZ" },
  { code: "8843", city: "Oberiberg", canton: "SZ" },
  { code: "8844", city: "Euthal", canton: "SZ" },
  { code: "8847", city: "Egg", canton: "SZ" },
  { code: "8852", city: "Altendorf", canton: "SZ" },
  { code: "8853", city: "Lachen", canton: "SZ" },
  { code: "8854", city: "Siebnen", canton: "SZ" },
  { code: "8855", city: "Wangen", canton: "SZ" },
  { code: "8856", city: "Tuggen", canton: "SZ" },
  { code: "8857", city: "Vorderthal", canton: "SZ" },
  { code: "8858", city: "Innerthal", canton: "SZ" },
  { code: "8862", city: "Schübelbach", canton: "SZ" },
  { code: "8863", city: "Buttikon", canton: "SZ" },
  { code: "8864", city: "Reichenburg", canton: "SZ" },
  { code: "8865", city: "Bilten", canton: "GL" },
  { code: "8866", city: "Ziegelbrücke", canton: "GL" },
  { code: "8867", city: "Niederurnen", canton: "GL" },
  { code: "8872", city: "Weesen", canton: "SG" },
  { code: "8873", city: "Amden", canton: "SG" },
  { code: "8874", city: "Mühlehorn", canton: "GL" },
  { code: "8877", city: "Murg", canton: "SG" },
  { code: "8880", city: "Walenstadt", canton: "SG" },
  { code: "8881", city: "Walenstadtberg", canton: "SG" },
  { code: "8882", city: "Unterterzen", canton: "SG" },
  { code: "8883", city: "Quarten", canton: "SG" },
  { code: "8884", city: "Oberterzen", canton: "SG" },
  { code: "8885", city: "Mols", canton: "SG" },
  { code: "8886", city: "Mädris-Vermol", canton: "SG" },
  { code: "8887", city: "Mels", canton: "SG" },
  { code: "8888", city: "Heiligkreuz (Mels)", canton: "SG" },
  { code: "8889", city: "Plons", canton: "SG" },
  { code: "8890", city: "Flums", canton: "SG" },
  { code: "8891", city: "Tscherlach", canton: "SG" },
  { code: "8892", city: "Berschis", canton: "SG" },
  { code: "8893", city: "Flums Hochwiese", canton: "SG" },
  { code: "8894", city: "Flumserberg Saxli", canton: "SG" },
  
  // Bern (BE) - Comprehensive coverage
  { code: "3000", city: "Bern", canton: "BE" },
  { code: "3001", city: "Bern", canton: "BE" },
  { code: "3003", city: "Bern", canton: "BE" },
  { code: "3004", city: "Bern", canton: "BE" },
  { code: "3005", city: "Bern", canton: "BE" },
  { code: "3006", city: "Bern", canton: "BE" },
  { code: "3007", city: "Bern", canton: "BE" },
  { code: "3008", city: "Bern", canton: "BE" },
  { code: "3010", city: "Bern", canton: "BE" },
  { code: "3011", city: "Bern", canton: "BE" },
  { code: "3012", city: "Bern", canton: "BE" },
  { code: "3013", city: "Bern", canton: "BE" },
  { code: "3014", city: "Bern", canton: "BE" },
  { code: "3015", city: "Bern", canton: "BE" },
  { code: "3018", city: "Bern", canton: "BE" },
  { code: "3019", city: "Bern", canton: "BE" },
  { code: "3020", city: "Bern", canton: "BE" },
  { code: "3027", city: "Bern", canton: "BE" },
  { code: "3028", city: "Spiegel", canton: "BE" },
  { code: "3032", city: "Hinterkappelen", canton: "BE" },
  { code: "3033", city: "Wohlen", canton: "BE" },
  { code: "3034", city: "Murzelen", canton: "BE" },
  { code: "3035", city: "Frieswil", canton: "BE" },
  { code: "3036", city: "Detligen", canton: "BE" },
  { code: "3037", city: "Herrenschwanden", canton: "BE" },
  { code: "3038", city: "Kirchlindach", canton: "BE" },
  { code: "3042", city: "Ortschwaben", canton: "BE" },
  { code: "3043", city: "Uettligen", canton: "BE" },
  { code: "3044", city: "Innerberg", canton: "BE" },
  { code: "3045", city: "Meikirch", canton: "BE" },
  { code: "3046", city: "Wahlendorf", canton: "BE" },
  { code: "3047", city: "Bremgarten", canton: "BE" },
  { code: "3048", city: "Worblaufen", canton: "BE" },
  { code: "3049", city: "Säriswil", canton: "BE" },
  { code: "3052", city: "Zollikofen", canton: "BE" },
  { code: "3053", city: "Münchenbuchsee", canton: "BE" },
  { code: "3054", city: "Schüpfen", canton: "BE" },
  { code: "3065", city: "Bolligen", canton: "BE" },
  { code: "3066", city: "Stettlen", canton: "BE" },
  { code: "3067", city: "Boll", canton: "BE" },
  { code: "3068", city: "Utzigen", canton: "BE" },
  { code: "3071", city: "Ostermundigen", canton: "BE" },
  { code: "3072", city: "Ostermundigen", canton: "BE" },
  { code: "3073", city: "Gümligen", canton: "BE" },
  { code: "3074", city: "Muri", canton: "BE" },
  { code: "3075", city: "Rüfenacht", canton: "BE" },
  { code: "3076", city: "Worb", canton: "BE" },
  { code: "3077", city: "Enggistein", canton: "BE" },
  { code: "3078", city: "Richigen", canton: "BE" },
  { code: "3082", city: "Schlosswil", canton: "BE" },
  { code: "3083", city: "Trimstein", canton: "BE" },
  { code: "3084", city: "Wabern", canton: "BE" },
  { code: "3086", city: "Zimmerwald", canton: "BE" },
  { code: "3087", city: "Niedermuhlern", canton: "BE" },
  { code: "3088", city: "Oberbütschel", canton: "BE" },
  { code: "3089", city: "Hinterfultigen", canton: "BE" },
  { code: "3095", city: "Spiegel", canton: "BE" },
  { code: "3096", city: "Oberbalm", canton: "BE" },
  { code: "3097", city: "Liebefeld", canton: "BE" },
  { code: "3098", city: "Köniz", canton: "BE" },
  { code: "3099", city: "Rüti", canton: "BE" },
  { code: "3250", city: "Lyss", canton: "BE" },
  { code: "3251", city: "Wengi", canton: "BE" },
  { code: "3252", city: "Worben", canton: "BE" },
  { code: "3253", city: "Schnottwil", canton: "SO" },
  { code: "3254", city: "Balm", canton: "BE" },
  { code: "3255", city: "Rapperswil", canton: "BE" },
  { code: "3256", city: "Dieterswil", canton: "BE" },
  { code: "3257", city: "Grossaffoltern", canton: "BE" },
  { code: "3264", city: "Diessbach", canton: "BE" },
  { code: "3270", city: "Aarberg", canton: "BE" },
  { code: "3271", city: "Radelfingen", canton: "BE" },
  { code: "3272", city: "Walperswil", canton: "BE" },
  { code: "3273", city: "Kappelen", canton: "BE" },
  { code: "3274", city: "Merzligen", canton: "BE" },
  { code: "3280", city: "Murten", canton: "FR" },
  { code: "3292", city: "Busswil", canton: "BE" },
  { code: "3294", city: "Büren an der Aare", canton: "BE" },
  { code: "3295", city: "Rüti", canton: "BE" },
  { code: "3296", city: "Arch", canton: "BE" },
  { code: "3297", city: "Leuzigen", canton: "BE" },
  { code: "3298", city: "Oberwil", canton: "BE" },
  { code: "3303", city: "Jegenstorf", canton: "BE" },
  { code: "3304", city: "Walperswil", canton: "BE" },
  { code: "3305", city: "Iffwil", canton: "BE" },
  { code: "3306", city: "Etzelkofen", canton: "BE" },
  { code: "3309", city: "Zauggenried", canton: "BE" },
  { code: "3312", city: "Fraubrunnen", canton: "BE" },
  { code: "3313", city: "Büren zum Hof", canton: "BE" },
  { code: "3314", city: "Schalunen", canton: "BE" },
  { code: "3315", city: "Bätterkinden", canton: "BE" },
  { code: "3317", city: "Limpach", canton: "BE" },
  { code: "3360", city: "Herzogenbuchsee", canton: "BE" },
  { code: "3400", city: "Burgdorf", canton: "BE" },
  { code: "3401", city: "Burgdorf", canton: "BE" },
  { code: "3412", city: "Heimiswil", canton: "BE" },
  { code: "3413", city: "Kaltacker", canton: "BE" },
  { code: "3414", city: "Oberburg", canton: "BE" },
  { code: "3415", city: "Hasle-Rüegsau", canton: "BE" },
  { code: "3416", city: "Affoltern im Emmental", canton: "BE" },
  { code: "3417", city: "Rüegsau", canton: "BE" },
  { code: "3418", city: "Rüegsbach", canton: "BE" },
  { code: "3419", city: "Biembach im Emmental", canton: "BE" },
  { code: "3421", city: "Lyssach", canton: "BE" },
  { code: "3422", city: "Kirchberg", canton: "BE" },
  { code: "3423", city: "Ersigen", canton: "BE" },
  { code: "3424", city: "Niederösch", canton: "BE" },
  { code: "3425", city: "Koppigen", canton: "BE" },
  { code: "3426", city: "Aefligen", canton: "BE" },
  { code: "3427", city: "Utzenstorf", canton: "BE" },
  { code: "3428", city: "Wiler", canton: "BE" },
  { code: "3429", city: "Hellsau", canton: "BE" },
  { code: "3432", city: "Lützelflüh-Goldbach", canton: "BE" },
  { code: "3433", city: "Schwanden im Emmental", canton: "BE" },
  { code: "3434", city: "Obergoldbach", canton: "BE" },
  { code: "3435", city: "Ramsei", canton: "BE" },
  { code: "3436", city: "Zollbrück", canton: "BE" },
  { code: "3437", city: "Rüderswil", canton: "BE" },
  { code: "3438", city: "Lauperswil", canton: "BE" },
  { code: "3439", city: "Ranflüh", canton: "BE" },
  { code: "3510", city: "Konolfingen", canton: "BE" },
  { code: "3600", city: "Thun", canton: "BE" },
  { code: "3601", city: "Thun", canton: "BE" },
  { code: "3602", city: "Thun", canton: "BE" },
  { code: "3603", city: "Thun", canton: "BE" },
  { code: "3604", city: "Thun", canton: "BE" },
  { code: "3608", city: "Thun", canton: "BE" },
  { code: "3612", city: "Steffisburg", canton: "BE" },
  { code: "3613", city: "Steffisburg", canton: "BE" },
  { code: "3614", city: "Unterlangenegg", canton: "BE" },
  { code: "3615", city: "Heimenschwand", canton: "BE" },
  { code: "3616", city: "Schwarzenegg", canton: "BE" },
  { code: "3617", city: "Fahrni", canton: "BE" },
  { code: "3618", city: "Süderen", canton: "BE" },
  { code: "3619", city: "Eriz", canton: "BE" },
  { code: "3622", city: "Homberg", canton: "BE" },
  { code: "3623", city: "Horrenbach", canton: "BE" },
  { code: "3624", city: "Goldiwil (Thun)", canton: "BE" },
  { code: "3625", city: "Heiligenschwendi", canton: "BE" },
  { code: "3626", city: "Hünibach", canton: "BE" },
  { code: "3627", city: "Heimberg", canton: "BE" },
  { code: "3628", city: "Uttigen", canton: "BE" },
  { code: "3629", city: "Kiesen", canton: "BE" },
  { code: "3631", city: "Höfen", canton: "BE" },
  { code: "3632", city: "Niederstocken", canton: "BE" },
  { code: "3633", city: "Amsoldingen", canton: "BE" },
  { code: "3634", city: "Thierachern", canton: "BE" },
  { code: "3635", city: "Uebeschi", canton: "BE" },
  { code: "3645", city: "Gwatt (Thun)", canton: "BE" },
  { code: "3646", city: "Einigen", canton: "BE" },
  { code: "3647", city: "Reutigen", canton: "BE" },
  { code: "3648", city: "Heiligenschwendi", canton: "BE" },
  { code: "3652", city: "Hilterfingen", canton: "BE" },
  { code: "3653", city: "Oberhofen am Thunersee", canton: "BE" },
  { code: "3654", city: "Gunten", canton: "BE" },
  { code: "3655", city: "Sigriswil", canton: "BE" },
  { code: "3656", city: "Ringoldswil", canton: "BE" },
  { code: "3657", city: "Schwanden", canton: "BE" },
  { code: "3658", city: "Merligen", canton: "BE" },
  { code: "3700", city: "Spiez", canton: "BE" },
  { code: "3702", city: "Hondrich", canton: "BE" },
  { code: "3703", city: "Aeschi", canton: "BE" },
  { code: "3704", city: "Krattigen", canton: "BE" },
  { code: "3705", city: "Faulensee", canton: "BE" },
  { code: "3706", city: "Leissigen", canton: "BE" },
  { code: "3707", city: "Därligen", canton: "BE" },
  { code: "3711", city: "Emdthal", canton: "BE" },
  { code: "3713", city: "Reichenbach im Kandertal", canton: "BE" },
  { code: "3714", city: "Frutigen", canton: "BE" },
  { code: "3715", city: "Adelboden", canton: "BE" },
  { code: "3716", city: "Kandergrund", canton: "BE" },
  { code: "3717", city: "Blausee-Mitholz", canton: "BE" },
  { code: "3718", city: "Kandersteg", canton: "BE" },
  { code: "3800", city: "Interlaken", canton: "BE" },
  { code: "3801", city: "Jungfraujoch", canton: "BE" },
  { code: "3803", city: "Beatenberg", canton: "BE" },
  { code: "3804", city: "Habkern", canton: "BE" },
  { code: "3805", city: "Goldswil", canton: "BE" },
  { code: "3806", city: "Bönigen", canton: "BE" },
  { code: "3807", city: "Iseltwald", canton: "BE" },
  { code: "3812", city: "Wilderswil", canton: "BE" },
  { code: "3813", city: "Saxeten", canton: "BE" },
  { code: "3814", city: "Gsteigwiler", canton: "BE" },
  { code: "3815", city: "Zweilütschinen", canton: "BE" },
  { code: "3816", city: "Lütschental", canton: "BE" },
  { code: "3818", city: "Grindelwald", canton: "BE" },
  { code: "3822", city: "Lauterbrunnen", canton: "BE" },
  { code: "3823", city: "Wengen", canton: "BE" },
  { code: "3824", city: "Stechelberg", canton: "BE" },
  { code: "3825", city: "Mürren", canton: "BE" },
  { code: "3826", city: "Gimmelwald", canton: "BE" },
  { code: "2500", city: "Biel/Bienne", canton: "BE" },
  { code: "2501", city: "Biel/Bienne", canton: "BE" },
  { code: "2502", city: "Biel/Bienne", canton: "BE" },
  { code: "2503", city: "Biel/Bienne", canton: "BE" },
  { code: "2504", city: "Biel/Bienne", canton: "BE" },
  { code: "2505", city: "Biel/Bienne", canton: "BE" },
  { code: "2512", city: "Tschugg", canton: "BE" },
  { code: "2513", city: "Twann", canton: "BE" },
  { code: "2514", city: "Ligerz", canton: "BE" },
  { code: "2515", city: "Prêles", canton: "BE" },
  { code: "2516", city: "Lamboing", canton: "BE" },
  { code: "2517", city: "Diesse", canton: "BE" },
  { code: "2518", city: "Nods", canton: "BE" },
  { code: "2520", city: "La Neuveville", canton: "BE" },
  { code: "2525", city: "Le Landeron", canton: "NE" },
  { code: "2532", city: "Magglingen/Macolin", canton: "BE" },
  { code: "2533", city: "Evilard", canton: "BE" },
  { code: "2534", city: "Orvin", canton: "BE" },
  { code: "2535", city: "Frinvillier", canton: "BE" },
  { code: "2536", city: "Plagne", canton: "BE" },
  { code: "2537", city: "Vauffelin", canton: "BE" },
  { code: "2538", city: "Romont", canton: "BE" },
  { code: "2540", city: "Grenchen", canton: "SO" },
  { code: "2542", city: "Pieterlen", canton: "BE" },
  { code: "2543", city: "Lengnau", canton: "BE" },
  { code: "2544", city: "Bettlach", canton: "SO" },
  { code: "2545", city: "Selzach", canton: "SO" },
  { code: "2552", city: "Orpund", canton: "BE" },
  { code: "2553", city: "Safnern", canton: "BE" },
  { code: "2554", city: "Meinisberg", canton: "BE" },
  { code: "2555", city: "Brügg", canton: "BE" },
  { code: "2556", city: "Scheuren", canton: "BE" },
  { code: "2557", city: "Studen", canton: "BE" },
  { code: "2558", city: "Aegerten", canton: "BE" },
  
  // Basel (BS/BL) - Comprehensive coverage
  { code: "4000", city: "Basel", canton: "BS" },
  { code: "4001", city: "Basel", canton: "BS" },
  { code: "4002", city: "Basel", canton: "BS" },
  { code: "4051", city: "Basel", canton: "BS" },
  { code: "4052", city: "Basel", canton: "BS" },
  { code: "4053", city: "Basel", canton: "BS" },
  { code: "4054", city: "Basel", canton: "BS" },
  { code: "4055", city: "Basel", canton: "BS" },
  { code: "4056", city: "Basel", canton: "BS" },
  { code: "4057", city: "Basel", canton: "BS" },
  { code: "4058", city: "Basel", canton: "BS" },
  { code: "4059", city: "Basel", canton: "BS" },
  { code: "4075", city: "Basel", canton: "BS" },
  { code: "4101", city: "Bruderholz", canton: "BL" },
  { code: "4102", city: "Binningen", canton: "BL" },
  { code: "4103", city: "Bottmingen", canton: "BL" },
  { code: "4104", city: "Oberwil", canton: "BL" },
  { code: "4105", city: "Biel-Benken", canton: "BL" },
  { code: "4106", city: "Therwil", canton: "BL" },
  { code: "4107", city: "Ettingen", canton: "BL" },
  { code: "4108", city: "Witterswil", canton: "SO" },
  { code: "4112", city: "Flüh", canton: "SO" },
  { code: "4114", city: "Hofstetten", canton: "SO" },
  { code: "4115", city: "Mariastein", canton: "SO" },
  { code: "4116", city: "Metzerlen", canton: "SO" },
  { code: "4117", city: "Burg im Leimental", canton: "BL" },
  { code: "4118", city: "Rodersdorf", canton: "SO" },
  { code: "4123", city: "Allschwil", canton: "BL" },
  { code: "4124", city: "Schönenbuch", canton: "BL" },
  { code: "4125", city: "Riehen", canton: "BS" },
  { code: "4126", city: "Bettingen", canton: "BS" },
  { code: "4127", city: "Birsfelden", canton: "BL" },
  { code: "4132", city: "Muttenz", canton: "BL" },
  { code: "4133", city: "Pratteln", canton: "BL" },
  { code: "4142", city: "Münchenstein", canton: "BL" },
  { code: "4143", city: "Dornach", canton: "SO" },
  { code: "4144", city: "Arlesheim", canton: "BL" },
  { code: "4145", city: "Gempen", canton: "SO" },
  { code: "4146", city: "Hochwald", canton: "SO" },
  { code: "4147", city: "Aesch", canton: "BL" },
  { code: "4148", city: "Pfeffingen", canton: "BL" },
  { code: "4153", city: "Reinach", canton: "BL" },
  { code: "4202", city: "Duggingen", canton: "BL" },
  { code: "4203", city: "Grellingen", canton: "BL" },
  { code: "4204", city: "Himmelried", canton: "SO" },
  { code: "4206", city: "Seewen", canton: "SO" },
  { code: "4207", city: "Bretzwil", canton: "BL" },
  { code: "4208", city: "Nunningen", canton: "SO" },
  { code: "4222", city: "Zwingen", canton: "BL" },
  { code: "4223", city: "Blauen", canton: "BL" },
  { code: "4224", city: "Nenzlingen", canton: "BL" },
  { code: "4225", city: "Brislach", canton: "BL" },
  { code: "4226", city: "Breitenbach", canton: "SO" },
  { code: "4227", city: "Büsserach", canton: "SO" },
  { code: "4228", city: "Erschwil", canton: "SO" },
  { code: "4229", city: "Beinwil", canton: "SO" },
  { code: "4242", city: "Laufen", canton: "BL" },
  { code: "4243", city: "Dittingen", canton: "BL" },
  { code: "4244", city: "Röschenz", canton: "BL" },
  { code: "4245", city: "Kleinlützel", canton: "SO" },
  { code: "4246", city: "Wahlen", canton: "BL" },
  { code: "4247", city: "Grindel", canton: "SO" },
  { code: "4253", city: "Liesberg", canton: "BL" },
  { code: "4254", city: "Liesberg Dorf", canton: "BL" },
  
  // Luzern (LU) - Comprehensive coverage
  { code: "6000", city: "Luzern", canton: "LU" },
  { code: "6003", city: "Luzern", canton: "LU" },
  { code: "6004", city: "Luzern", canton: "LU" },
  { code: "6005", city: "Luzern", canton: "LU" },
  { code: "6006", city: "Luzern", canton: "LU" },
  { code: "6010", city: "Kriens", canton: "LU" },
  { code: "6012", city: "Obernau", canton: "LU" },
  { code: "6013", city: "Eigenthal", canton: "LU" },
  { code: "6014", city: "Luzern", canton: "LU" },
  { code: "6015", city: "Luzern", canton: "LU" },
  { code: "6016", city: "Hellbühl", canton: "LU" },
  { code: "6017", city: "Ruswil", canton: "LU" },
  { code: "6018", city: "Buttisholz", canton: "LU" },
  { code: "6020", city: "Emmenbrücke", canton: "LU" },
  { code: "6021", city: "Emmenbrücke", canton: "LU" },
  { code: "6022", city: "Grosswangen", canton: "LU" },
  { code: "6023", city: "Rothenburg", canton: "LU" },
  { code: "6024", city: "Hildisrieden", canton: "LU" },
  { code: "6025", city: "Neudorf", canton: "LU" },
  { code: "6026", city: "Rain", canton: "LU" },
  { code: "6027", city: "Römerswil", canton: "LU" },
  { code: "6028", city: "Herlisberg", canton: "LU" },
  { code: "6030", city: "Ebikon", canton: "LU" },
  { code: "6032", city: "Emmen", canton: "LU" },
  { code: "6033", city: "Buchrain", canton: "LU" },
  { code: "6034", city: "Inwil", canton: "LU" },
  { code: "6035", city: "Perlen", canton: "LU" },
  { code: "6036", city: "Dierikon", canton: "LU" },
  { code: "6037", city: "Root", canton: "LU" },
  { code: "6038", city: "Gisikon", canton: "LU" },
  { code: "6039", city: "Root Längenbold", canton: "LU" },
  { code: "6042", city: "Dietwil", canton: "AG" },
  { code: "6043", city: "Adligenswil", canton: "LU" },
  { code: "6044", city: "Udligenswil", canton: "LU" },
  { code: "6045", city: "Meggen", canton: "LU" },
  { code: "6047", city: "Kastanienbaum", canton: "LU" },
  { code: "6048", city: "Horw", canton: "LU" },
  { code: "6052", city: "Hergiswil", canton: "NW" },
  { code: "6053", city: "Alpnachstad", canton: "OW" },
  { code: "6054", city: "Kerns", canton: "OW" },
  { code: "6055", city: "Alpnach Dorf", canton: "OW" },
  { code: "6056", city: "Kägiswil", canton: "OW" },
  { code: "6060", city: "Sarnen", canton: "OW" },
  { code: "6061", city: "Sarnen", canton: "OW" },
  { code: "6062", city: "Wilen (Sarnen)", canton: "OW" },
  { code: "6063", city: "Stalden (Sarnen)", canton: "OW" },
  { code: "6064", city: "Kerns", canton: "OW" },
  { code: "6072", city: "Sachseln", canton: "OW" },
  { code: "6073", city: "Flüeli-Ranft", canton: "OW" },
  { code: "6074", city: "Giswil", canton: "OW" },
  { code: "6078", city: "Bürglen", canton: "OW" },
  { code: "6083", city: "Hasliberg Hohfluh", canton: "BE" },
  { code: "6084", city: "Hasliberg Wasserwendi", canton: "BE" },
  { code: "6085", city: "Hasliberg Goldern", canton: "BE" },
  { code: "6086", city: "Hasliberg Reuti", canton: "BE" },
  { code: "6102", city: "Malters", canton: "LU" },
  { code: "6103", city: "Schwarzenberg", canton: "LU" },
  { code: "6105", city: "Schachen", canton: "LU" },
  { code: "6106", city: "Werthenstein", canton: "LU" },
  { code: "6110", city: "Wolhusen", canton: "LU" },
  { code: "6112", city: "Doppleschwand", canton: "LU" },
  { code: "6113", city: "Romoos", canton: "LU" },
  { code: "6114", city: "Steinhuserberg", canton: "LU" },
  { code: "6122", city: "Menznau", canton: "LU" },
  { code: "6123", city: "Geiss", canton: "LU" },
  { code: "6124", city: "Holzhäusern", canton: "LU" },
  { code: "6125", city: "Menzberg", canton: "LU" },
  { code: "6126", city: "Daiwil", canton: "LU" },
  { code: "6130", city: "Willisau", canton: "LU" },
  { code: "6132", city: "Rohrmatt", canton: "LU" },
  { code: "6133", city: "Hergiswil bei Willisau", canton: "LU" },
  { code: "6144", city: "Zell", canton: "LU" },
  { code: "6145", city: "Fischbach", canton: "LU" },
  { code: "6146", city: "Grossdietwil", canton: "LU" },
  { code: "6147", city: "Altbüron", canton: "LU" },
  { code: "6152", city: "Hüswil", canton: "LU" },
  { code: "6153", city: "Ufhusen", canton: "LU" },
  { code: "6154", city: "Hofstatt", canton: "LU" },
  { code: "6156", city: "Luthern", canton: "LU" },
  { code: "6162", city: "Entlebuch", canton: "LU" },
  { code: "6163", city: "Ebnet", canton: "LU" },
  { code: "6166", city: "Hasle", canton: "LU" },
  { code: "6167", city: "Bramboden", canton: "LU" },
  { code: "6170", city: "Schüpfheim", canton: "LU" },
  { code: "6182", city: "Escholzmatt", canton: "LU" },
  { code: "6192", city: "Wiggen", canton: "LU" },
  { code: "6196", city: "Marbach", canton: "LU" },
  
  // St. Gallen (SG) - Comprehensive coverage
  { code: "9000", city: "St. Gallen", canton: "SG" },
  { code: "9001", city: "St. Gallen", canton: "SG" },
  { code: "9004", city: "St. Gallen", canton: "SG" },
  { code: "9006", city: "St. Gallen", canton: "SG" },
  { code: "9008", city: "St. Gallen", canton: "SG" },
  { code: "9010", city: "St. Gallen", canton: "SG" },
  { code: "9011", city: "St. Gallen", canton: "SG" },
  { code: "9012", city: "St. Gallen", canton: "SG" },
  { code: "9014", city: "St. Gallen", canton: "SG" },
  { code: "9015", city: "St. Gallen", canton: "SG" },
  { code: "9016", city: "St. Gallen", canton: "SG" },
  { code: "9030", city: "Abtwil", canton: "SG" },
  { code: "9032", city: "Engelburg", canton: "SG" },
  { code: "9033", city: "Untereggen", canton: "SG" },
  { code: "9034", city: "Eggersriet", canton: "SG" },
  { code: "9035", city: "Grub", canton: "AR" },
  { code: "9036", city: "Grub", canton: "SG" },
  { code: "9037", city: "Speicherschwendi", canton: "AR" },
  { code: "9038", city: "Rehetobel", canton: "AR" },
  { code: "9042", city: "Speicher", canton: "AR" },
  { code: "9043", city: "Trogen", canton: "AR" },
  { code: "9044", city: "Wald", canton: "AR" },
  { code: "9050", city: "Appenzell", canton: "AI" },
  { code: "9052", city: "Niederteufen", canton: "AR" },
  { code: "9053", city: "Teufen", canton: "AR" },
  { code: "9054", city: "Haslen", canton: "AI" },
  { code: "9055", city: "Bühler", canton: "AR" },
  { code: "9056", city: "Gais", canton: "AR" },
  { code: "9057", city: "Weissbad", canton: "AI" },
  { code: "9058", city: "Brülisau", canton: "AI" },
  { code: "9062", city: "Lustmühle", canton: "AR" },
  { code: "9063", city: "Stein", canton: "AR" },
  { code: "9064", city: "Hundwil", canton: "AR" },
  { code: "9100", city: "Herisau", canton: "AR" },
  { code: "9101", city: "Herisau", canton: "AR" },
  { code: "9103", city: "Schwellbrunn", canton: "AR" },
  { code: "9104", city: "Waldstatt", canton: "AR" },
  { code: "9105", city: "Schönengrund", canton: "AR" },
  { code: "9107", city: "Urnäsch", canton: "AR" },
  { code: "9108", city: "Gonten", canton: "AI" },
  { code: "9112", city: "Schachen", canton: "AR" },
  { code: "9113", city: "Degersheim", canton: "SG" },
  { code: "9114", city: "Hoffeld", canton: "SG" },
  { code: "9115", city: "Dicken", canton: "SG" },
  { code: "9200", city: "Gossau", canton: "SG" },
  { code: "9201", city: "Gossau", canton: "SG" },
  { code: "9203", city: "Niederwil", canton: "SG" },
  { code: "9204", city: "Andwil", canton: "SG" },
  { code: "9205", city: "Waldkirch", canton: "SG" },
  { code: "9212", city: "Arnegg", canton: "SG" },
  { code: "9213", city: "Hauptwil", canton: "TG" },
  { code: "9214", city: "Kradolf", canton: "TG" },
  { code: "9215", city: "Schönenberg an der Thur", canton: "TG" },
  { code: "9216", city: "Heldswil", canton: "TG" },
  { code: "9220", city: "Bischofszell", canton: "TG" },
  { code: "9222", city: "Kössen", canton: "TG" },
  { code: "9223", city: "Schweizersholz", canton: "TG" },
  { code: "9300", city: "Wittenbach", canton: "SG" },
  { code: "9305", city: "Berg", canton: "SG" },
  { code: "9306", city: "Freidorf", canton: "TG" },
  { code: "9308", city: "Lömmenschwil", canton: "SG" },
  { code: "9312", city: "Häggenschwil", canton: "SG" },
  { code: "9313", city: "Muolen", canton: "SG" },
  { code: "9314", city: "Steinebrunn", canton: "TG" },
  { code: "9315", city: "Neukirch (Egnach)", canton: "TG" },
  { code: "9320", city: "Arbon", canton: "TG" },
  { code: "9323", city: "Steinach", canton: "SG" },
  { code: "9325", city: "Roggwil", canton: "TG" },
  { code: "9326", city: "Horn", canton: "TG" },
  { code: "9327", city: "Tübach", canton: "SG" },
  { code: "9400", city: "Rorschach", canton: "SG" },
  { code: "9402", city: "Mörschwil", canton: "SG" },
  { code: "9403", city: "Goldach", canton: "SG" },
  { code: "9404", city: "Rorschacherberg", canton: "SG" },
  { code: "9405", city: "Wienacht-Tobel", canton: "AR" },
  { code: "9410", city: "Heiden", canton: "AR" },
  { code: "9411", city: "Reute", canton: "AR" },
  { code: "9413", city: "Oberegg", canton: "AI" },
  { code: "9422", city: "Staad", canton: "SG" },
  { code: "9423", city: "Altenrhein", canton: "SG" },
  { code: "9424", city: "Rheineck", canton: "SG" },
  { code: "9425", city: "Thal", canton: "SG" },
  { code: "9426", city: "Lutzenberg", canton: "AR" },
  { code: "9427", city: "Wolfhalden", canton: "AR" },
  { code: "9428", city: "Walzenhausen", canton: "AR" },
  { code: "9430", city: "St. Margrethen", canton: "SG" },
  { code: "9434", city: "Au", canton: "SG" },
  { code: "9435", city: "Heerbrugg", canton: "SG" },
  { code: "9436", city: "Balgach", canton: "SG" },
  { code: "9437", city: "Marbach", canton: "SG" },
  { code: "9442", city: "Berneck", canton: "SG" },
  { code: "9443", city: "Widnau", canton: "SG" },
  { code: "9444", city: "Diepoldsau", canton: "SG" },
  { code: "9445", city: "Rebstein", canton: "SG" },
  { code: "9450", city: "Altstätten", canton: "SG" },
  { code: "9451", city: "Kriessern", canton: "SG" },
  { code: "9452", city: "Hinterforst", canton: "SG" },
  { code: "9453", city: "Eichberg", canton: "SG" },
  { code: "9462", city: "Montlingen", canton: "SG" },
  { code: "9463", city: "Oberriet", canton: "SG" },
  { code: "9464", city: "Rüthi", canton: "SG" },
  { code: "9465", city: "Salez", canton: "SG" },
  { code: "9466", city: "Sennwald", canton: "SG" },
  { code: "9467", city: "Frümsen", canton: "SG" },
  { code: "9468", city: "Sax", canton: "SG" },
  { code: "9469", city: "Haag (Rheintal)", canton: "SG" },
  { code: "9470", city: "Buchs", canton: "SG" },
  { code: "9471", city: "Buchs", canton: "SG" },
  { code: "9472", city: "Grabs", canton: "SG" },
  { code: "9473", city: "Gams", canton: "SG" },
  { code: "9475", city: "Sevelen", canton: "SG" },
  { code: "9476", city: "Weite", canton: "SG" },
  { code: "9477", city: "Trübbach", canton: "SG" },
  { code: "9478", city: "Azmoos", canton: "SG" },
  { code: "9479", city: "Oberschan", canton: "SG" },
  { code: "9485", city: "Nendeln", canton: "FL" },
  { code: "9486", city: "Schaanwald", canton: "FL" },
  { code: "9487", city: "Gamprin-Bendern", canton: "FL" },
  { code: "9488", city: "Schellenberg", canton: "FL" },
  { code: "9489", city: "Vaduz", canton: "FL" },
  { code: "9490", city: "Vaduz", canton: "FL" },
  { code: "9491", city: "Ruggell", canton: "FL" },
  { code: "9492", city: "Eschen", canton: "FL" },
  { code: "9493", city: "Mauren", canton: "FL" },
  { code: "9494", city: "Schaan", canton: "FL" },
  { code: "9495", city: "Triesen", canton: "FL" },
  { code: "9496", city: "Balzers", canton: "FL" },
  { code: "9497", city: "Triesenberg", canton: "FL" },
  { code: "9498", city: "Planken", canton: "FL" },
  
  // Genève (GE) - Comprehensive coverage
  { code: "1200", city: "Genève", canton: "GE" },
  { code: "1201", city: "Genève", canton: "GE" },
  { code: "1202", city: "Genève", canton: "GE" },
  { code: "1203", city: "Genève", canton: "GE" },
  { code: "1204", city: "Genève", canton: "GE" },
  { code: "1205", city: "Genève", canton: "GE" },
  { code: "1206", city: "Genève", canton: "GE" },
  { code: "1207", city: "Genève", canton: "GE" },
  { code: "1208", city: "Genève", canton: "GE" },
  { code: "1209", city: "Genève", canton: "GE" },
  { code: "1210", city: "Genève", canton: "GE" },
  { code: "1211", city: "Genève", canton: "GE" },
  { code: "1212", city: "Grand-Lancy", canton: "GE" },
  { code: "1213", city: "Petit-Lancy", canton: "GE" },
  { code: "1214", city: "Vernier", canton: "GE" },
  { code: "1215", city: "Genève", canton: "GE" },
  { code: "1216", city: "Cointrin", canton: "GE" },
  { code: "1217", city: "Meyrin", canton: "GE" },
  { code: "1218", city: "Le Grand-Saconnex", canton: "GE" },
  { code: "1219", city: "Le Lignon", canton: "GE" },
  { code: "1220", city: "Les Avanchets", canton: "GE" },
  { code: "1222", city: "Vésenaz", canton: "GE" },
  { code: "1223", city: "Cologny", canton: "GE" },
  { code: "1224", city: "Chêne-Bougeries", canton: "GE" },
  { code: "1225", city: "Chêne-Bourg", canton: "GE" },
  { code: "1226", city: "Thônex", canton: "GE" },
  { code: "1227", city: "Carouge", canton: "GE" },
  { code: "1228", city: "Plan-les-Ouates", canton: "GE" },
  { code: "1231", city: "Conches", canton: "GE" },
  { code: "1232", city: "Confignon", canton: "GE" },
  { code: "1233", city: "Bernex", canton: "GE" },
  { code: "1234", city: "Vessy", canton: "GE" },
  { code: "1236", city: "Cartigny", canton: "GE" },
  { code: "1237", city: "Avully", canton: "GE" },
  { code: "1239", city: "Collex", canton: "GE" },
  { code: "1240", city: "Genève", canton: "GE" },
  { code: "1241", city: "Puplinge", canton: "GE" },
  { code: "1242", city: "Satigny", canton: "GE" },
  { code: "1243", city: "Presinge", canton: "GE" },
  { code: "1244", city: "Choulex", canton: "GE" },
  { code: "1245", city: "Collonge-Bellerive", canton: "GE" },
  { code: "1246", city: "Corsier", canton: "GE" },
  { code: "1247", city: "Anières", canton: "GE" },
  { code: "1248", city: "Hermance", canton: "GE" },
  { code: "1251", city: "Gy", canton: "GE" },
  { code: "1252", city: "Meinier", canton: "GE" },
  { code: "1253", city: "Vandoeuvres", canton: "GE" },
  { code: "1254", city: "Jussy", canton: "GE" },
  { code: "1255", city: "Veyrier", canton: "GE" },
  { code: "1256", city: "Troinex", canton: "GE" },
  { code: "1257", city: "La Croix-de-Rozon", canton: "GE" },
  { code: "1258", city: "Perly", canton: "GE" },
  { code: "1260", city: "Nyon", canton: "VD" },
  { code: "1261", city: "Longirod", canton: "VD" },
  { code: "1262", city: "Eysins", canton: "VD" },
  { code: "1263", city: "Crassier", canton: "VD" },
  { code: "1264", city: "St-Cergue", canton: "VD" },
  { code: "1265", city: "La Cure", canton: "VD" },
  { code: "1266", city: "Duillier", canton: "VD" },
  { code: "1267", city: "Vich", canton: "VD" },
  { code: "1268", city: "Begnins", canton: "VD" },
  { code: "1269", city: "Bassins", canton: "VD" },
  { code: "1270", city: "Trélex", canton: "VD" },
  { code: "1271", city: "Givrins", canton: "VD" },
  { code: "1272", city: "Genolier", canton: "VD" },
  { code: "1273", city: "Arzier-Le Muids", canton: "VD" },
  { code: "1274", city: "Signy", canton: "VD" },
  { code: "1275", city: "Chéserex", canton: "VD" },
  { code: "1276", city: "Gingins", canton: "VD" },
  { code: "1277", city: "Borex", canton: "VD" },
  { code: "1278", city: "La Rippe", canton: "VD" },
  { code: "1279", city: "Chavannes-de-Bogis", canton: "VD" },
  { code: "1281", city: "Russin", canton: "GE" },
  { code: "1283", city: "Dardagny", canton: "GE" },
  { code: "1284", city: "Chancy", canton: "GE" },
  { code: "1285", city: "Athenaz (Avusy)", canton: "GE" },
  { code: "1286", city: "Soral", canton: "GE" },
  { code: "1287", city: "Laconnex", canton: "GE" },
  { code: "1288", city: "Aire-la-Ville", canton: "GE" },
  { code: "1290", city: "Versoix", canton: "GE" },
  { code: "1291", city: "Commugny", canton: "VD" },
  { code: "1292", city: "Chambésy", canton: "GE" },
  { code: "1293", city: "Bellevue", canton: "GE" },
  { code: "1294", city: "Genthod", canton: "GE" },
  { code: "1295", city: "Mies", canton: "VD" },
  { code: "1296", city: "Coppet", canton: "VD" },
  { code: "1297", city: "Founex", canton: "VD" },
  { code: "1298", city: "Céligny", canton: "GE" },
  { code: "1299", city: "Crans-près-Céligny", canton: "VD" },
  
  // Lausanne (VD) - Comprehensive coverage
  { code: "1000", city: "Lausanne", canton: "VD" },
  { code: "1003", city: "Lausanne", canton: "VD" },
  { code: "1004", city: "Lausanne", canton: "VD" },
  { code: "1005", city: "Lausanne", canton: "VD" },
  { code: "1006", city: "Lausanne", canton: "VD" },
  { code: "1007", city: "Lausanne", canton: "VD" },
  { code: "1008", city: "Prilly", canton: "VD" },
  { code: "1009", city: "Pully", canton: "VD" },
  { code: "1010", city: "Lausanne", canton: "VD" },
  { code: "1011", city: "Lausanne", canton: "VD" },
  { code: "1012", city: "Lausanne", canton: "VD" },
  { code: "1018", city: "Lausanne", canton: "VD" },
  { code: "1020", city: "Renens", canton: "VD" },
  { code: "1022", city: "Chavannes-près-Renens", canton: "VD" },
  { code: "1023", city: "Crissier", canton: "VD" },
  { code: "1024", city: "Ecublens", canton: "VD" },
  { code: "1025", city: "St-Sulpice", canton: "VD" },
  { code: "1026", city: "Echandens", canton: "VD" },
  { code: "1027", city: "Lonay", canton: "VD" },
  { code: "1028", city: "Préverenges", canton: "VD" },
  { code: "1029", city: "Villars-Ste-Croix", canton: "VD" },
  { code: "1030", city: "Bussigny", canton: "VD" },
  { code: "1031", city: "Mex", canton: "VD" },
  { code: "1032", city: "Romanel-sur-Lausanne", canton: "VD" },
  { code: "1033", city: "Cheseaux-sur-Lausanne", canton: "VD" },
  { code: "1034", city: "Boussens", canton: "VD" },
  { code: "1035", city: "Bournens", canton: "VD" },
  { code: "1036", city: "Sullens", canton: "VD" },
  { code: "1037", city: "Etagnières", canton: "VD" },
  { code: "1038", city: "Bercher", canton: "VD" },
  { code: "1039", city: "Cheseaux-Noréaz", canton: "VD" },
  { code: "1040", city: "Echallens", canton: "VD" },
  { code: "1041", city: "Dommartin", canton: "VD" },
  { code: "1042", city: "Assens", canton: "VD" },
  { code: "1043", city: "Sugnens", canton: "VD" },
  { code: "1044", city: "Fey", canton: "VD" },
  { code: "1045", city: "Ogens", canton: "VD" },
  { code: "1046", city: "Rueyres", canton: "VD" },
  { code: "1047", city: "Oppens", canton: "VD" },
  { code: "1052", city: "Le Mont-sur-Lausanne", canton: "VD" },
  { code: "1053", city: "Cugy", canton: "VD" },
  { code: "1054", city: "Morrens", canton: "VD" },
  { code: "1055", city: "Froideville", canton: "VD" },
  { code: "1058", city: "Villars-Tiercelin", canton: "VD" },
  { code: "1059", city: "Peney-le-Jorat", canton: "VD" },
  { code: "1061", city: "Villars-Mendraz", canton: "VD" },
  { code: "1062", city: "Sottens", canton: "VD" },
  { code: "1063", city: "Chapelle-sur-Moudon", canton: "VD" },
  { code: "1066", city: "Epalinges", canton: "VD" },
  { code: "1068", city: "Les Monts-de-Pully", canton: "VD" },
  { code: "1070", city: "Puidoux", canton: "VD" },
  { code: "1071", city: "Chexbres", canton: "VD" },
  { code: "1072", city: "Forel (Lavaux)", canton: "VD" },
  { code: "1073", city: "Savigny", canton: "VD" },
  { code: "1076", city: "Ferlens", canton: "VD" },
  { code: "1077", city: "Servion", canton: "VD" },
  { code: "1078", city: "Essertes", canton: "VD" },
  { code: "1082", city: "Corcelles-le-Jorat", canton: "VD" },
  { code: "1083", city: "Mézières", canton: "VD" },
  { code: "1084", city: "Carrouge", canton: "VD" },
  { code: "1085", city: "Vulliens", canton: "VD" },
  { code: "1088", city: "Ropraz", canton: "VD" },
  { code: "1090", city: "La Croix (Lutry)", canton: "VD" },
  { code: "1091", city: "Grandvaux", canton: "VD" },
  { code: "1092", city: "Belmont-sur-Lausanne", canton: "VD" },
  { code: "1093", city: "La Conversion", canton: "VD" },
  { code: "1094", city: "Paudex", canton: "VD" },
  { code: "1095", city: "Lutry", canton: "VD" },
  { code: "1096", city: "Cully", canton: "VD" },
  { code: "1097", city: "Riex", canton: "VD" },
  { code: "1098", city: "Epesses", canton: "VD" },
  
  // Zug (ZG) - Complete coverage
  { code: "6300", city: "Zug", canton: "ZG" },
  { code: "6301", city: "Zug", canton: "ZG" },
  { code: "6302", city: "Zug", canton: "ZG" },
  { code: "6303", city: "Zug", canton: "ZG" },
  { code: "6304", city: "Zug", canton: "ZG" },
  { code: "6310", city: "Zug", canton: "ZG" },
  { code: "6312", city: "Steinhausen", canton: "ZG" },
  { code: "6313", city: "Menzingen", canton: "ZG" },
  { code: "6314", city: "Unterägeri", canton: "ZG" },
  { code: "6315", city: "Oberägeri", canton: "ZG" },
  { code: "6317", city: "Oberwil", canton: "ZG" },
  { code: "6318", city: "Walchwil", canton: "ZG" },
  { code: "6319", city: "Allenwinden", canton: "ZG" },
  { code: "6330", city: "Cham", canton: "ZG" },
  { code: "6331", city: "Hünenberg", canton: "ZG" },
  { code: "6332", city: "Hagendorn", canton: "ZG" },
  { code: "6333", city: "Hünenberg See", canton: "ZG" },
  { code: "6340", city: "Baar", canton: "ZG" },
  { code: "6341", city: "Baar", canton: "ZG" },
  { code: "6343", city: "Rotkreuz", canton: "ZG" },
  { code: "6344", city: "Meierskappel", canton: "LU" },
  { code: "6345", city: "Neuheim", canton: "ZG" },
  { code: "6349", city: "Baar", canton: "ZG" },

  // Additional major cities
  { code: "5000", city: "Aarau", canton: "AG" },
  { code: "6900", city: "Lugano", canton: "TI" },
  { code: "7000", city: "Chur", canton: "GR" },
  { code: "2000", city: "Neuchâtel", canton: "NE" },
  { code: "1700", city: "Fribourg", canton: "FR" },
  { code: "4500", city: "Solothurn", canton: "SO" },
  { code: "6460", city: "Altdorf", canton: "UR" },
  { code: "6440", city: "Brunnen", canton: "SZ" },
  { code: "3900", city: "Brig", canton: "VS" },
  { code: "1950", city: "Sion", canton: "VS" },
  { code: "3930", city: "Visp", canton: "VS" },
];

export const searchPostalCodes = (query: string): PostalCodeEntry[] => {
  if (!query || query.length < 2) return [];
  
  const lowerQuery = query.toLowerCase();
  
  return swissPostalCodes
    .filter(entry => 
      entry.code.includes(query) || 
      entry.city.toLowerCase().includes(lowerQuery)
    )
    .slice(0, 10); // Limit to 10 results
};

export const getPostalCodeInfo = (code: string): PostalCodeEntry | undefined => {
  return swissPostalCodes.find(entry => entry.code === code);
};

export const validatePostalCode = (code: string): boolean => {
  return /^\d{4}$/.test(code) && swissPostalCodes.some(entry => entry.code === code);
};
