project_id = "vgitgdvxanodfgokokix"

[functions.fetch-html]
verify_jwt = false

[functions.scheduled-screenshots]
verify_jwt = false

[functions.lighthouse]
verify_jwt = false

[functions.capture-screenshot]
verify_jwt = false
