#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read tokens.json
const tokensPath = path.resolve(__dirname, "../src/tokens/feierabend.tokens.json");
const tokensData = JSON.parse(fs.readFileSync(tokensPath, "utf-8"));

// Helper: Resolve {reference} values
function resolveValue(value, allTokens) {
  if (typeof value !== "string") return value;
  if (!value.startsWith("{") || !value.endsWith("}")) return value;

  const refPath = value.slice(1, -1).split(".");
  let current = allTokens;
  for (const key of refPath) {
    current = current[key];
    if (!current) return value; // Return original if not found
  }
  return current?.value || value;
}

// Flatten all tokens to CSS variables
function flattenTokens(obj, prefix = "", result = {}) {
  for (const [key, val] of Object.entries(obj)) {
    if (val === null || val === undefined) continue;

    const cssVarName = prefix ? `${prefix}-${key}` : key;

    if (val.type === "color" && val.value) {
      // Resolve references
      const resolvedValue = resolveValue(val.value, tokensData.color?.palette || {});
      result[`--color-${cssVarName}`] = resolvedValue;
    } else if (typeof val === "object" && !val.type) {
      flattenTokens(val, cssVarName, result);
    } else if (val.type && val.value) {
      // Generic token type
      const resolvedValue = resolveValue(val.value, tokensData);
      result[`--${cssVarName}`] = resolvedValue;
    }
  }
  return result;
}

// Semantic mapping (hand-crafted for brand consistency)
const semantic = tokensData.color?.semantic ?? {};
const semanticTokens = {
  // Brand
  "--color-semantic-brand-primary":
    resolveValue(semantic.brand?.primary?.value, tokensData) ||
    tokensData.color?.palette?.brand?.blue?.[500]?.value ||
    "#008080",
  "--color-semantic-brand-secondary":
    resolveValue(semantic.brand?.secondary?.value, tokensData) ||
    tokensData.color?.palette?.brand?.orange?.[500]?.value ||
    "#FF6B1A",
  "--color-semantic-brand-muted":
    resolveValue(semantic.brand?.muted?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.slate?.[50]?.value ||
    "#F8FAFC",

  // Action
  "--color-semantic-action-default":
    resolveValue(semantic.action?.default?.value, tokensData) ||
    tokensData.color?.palette?.brand?.orange?.[500]?.value ||
    "#FF6B1A",
  "--color-semantic-action-hover":
    resolveValue(semantic.action?.hover?.value, tokensData) ||
    tokensData.color?.palette?.brand?.orange?.[600]?.value ||
    "#F04E00",
  "--color-semantic-action-disabled":
    resolveValue(semantic.action?.disabled?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.slate?.[200]?.value ||
    "#E2E8F0",

  // Text
  "--color-semantic-text-main":
    resolveValue(semantic.text?.main?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.slate?.[900]?.value ||
    "#0F172A",
  "--color-semantic-text-heading":
    resolveValue(semantic.text?.heading?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.black?.value ||
    "#0B0F17",
  "--color-semantic-text-inverted":
    resolveValue(semantic.text?.inverted?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.white?.value ||
    "#FFFFFF",
  "--color-semantic-text-link":
    resolveValue(semantic.text?.link?.value, tokensData) ||
    tokensData.color?.palette?.brand?.blue?.[700]?.value ||
    "#004D4D",

  // Background
  "--color-semantic-background-canvas":
    resolveValue(semantic.background?.canvas?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.white?.value ||
    "#FFFFFF",
  "--color-semantic-background-surface":
    resolveValue(semantic.background?.surface?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.white?.value ||
    "#FFFFFF",
  "--color-semantic-background-highlight":
    resolveValue(semantic.background?.highlight?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.slate?.[50]?.value ||
    "#F8FAFC",

  // Border
  "--color-semantic-border-default":
    resolveValue(semantic.border?.default?.value, tokensData) ||
    tokensData.color?.palette?.neutral?.slate?.[300]?.value ||
    "#CBD5E1",
  "--color-semantic-border-active":
    resolveValue(semantic.border?.active?.value, tokensData) ||
    tokensData.color?.palette?.brand?.blue?.[500]?.value ||
    "#008080",
};
// Flatten all tokens
const flatTokens = flattenTokens(tokensData);

// Merge with semantic tokens
const allCSSVars = { ...flatTokens, ...semanticTokens };

// Generate CSS
const cssLines = [
  "/* Auto-generated by build-tokens.mjs - DO NOT EDIT MANUALLY */",
  "/* Generated: " + new Date().toISOString() + " */",
  "",
  ":root {",
];

for (const [name, value] of Object.entries(allCSSVars)) {
  if (value) {
    cssLines.push(`  ${name}: ${value};`);
  }
}

cssLines.push("}");
cssLines.push("");

const cssContent = cssLines.join("\n");

// Write to src/styles/tokens.css
const outputPath = path.resolve(__dirname, "../src/styles/tokens.css");
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, cssContent, "utf-8");

console.log(`✅ Tokens generated: ${outputPath}`);
console.log(`📊 Total CSS variables: ${Object.keys(allCSSVars).length}`);






