// Mobile-optimized hooks
export { useSwipeGesture } from '../useSwipeGesture';
export { usePageSwipeNavigation } from '../usePageSwipeNavigation';
export { useHaptic } from '../use-haptic';
export { useIsMobile } from '../use-mobile';
export { useKeyboardAwareScroll } from '../useKeyboardAwareScroll';
export { useGestureNavigation } from '../useGestureNavigation';
export { useDarkMode } from '../useDarkMode';
export { usePullToRefresh } from '../usePullToRefresh';
export { useOfflineDetection } from '../useOfflineDetection';
export { useScrollDirection } from '../useScrollDirection';
export { useLockBodyScroll } from '../useLockBodyScroll';
export { useNetworkStatus } from '../useNetworkStatus';
export { useDeviceOrientation } from '../useDeviceOrientation';
export { usePushNotifications } from '../usePushNotifications';
export { useBiometricAuth } from '../useBiometricAuth';
export { useVoiceInput } from '../useVoiceInput';
export { useDoubleTap } from '../useDoubleTap';
export { useLongPress } from '../useLongPress';
export { usePinchZoom } from '../usePinchZoom';
export { useShareAPI } from '../useShareAPI';
export { useClipboard } from '../useClipboard';
export { useInstallPrompt } from '../useInstallPrompt';
export { useFullscreen } from '../useFullscreen';
export { useScreenWakeLock } from '../useScreenWakeLock';
export { useDeviceMotion } from '../useDeviceMotion';
export { useCamera } from '../useCamera';
export { useIndexedDB } from '../useIndexedDB';
export { useOfflineSync } from '../useOfflineSync';
export { useQRScanner } from '../useQRScanner';
export { useGeolocation } from '../useGeolocation';
export { useBatteryStatus } from '../useBatteryStatus';
export { useVibration } from '../useVibration';
export { useMediaQuery, useIsMobile as useIsMobileQuery, useIsTablet, useIsDesktop, usePrefersDarkMode, usePrefersReducedMotion, useIsLandscape, useIsPortrait, useIsTouchDevice } from '../useMediaQuery';
export { useLocalStorage } from '../useLocalStorage';
export { useSessionStorage } from '../useSessionStorage';
export { useWindowSize } from '../useWindowSize';
export { useScrollPosition } from '../useScrollPosition';
export { useFormPersistence } from '../useFormPersistence';
export { useImageGallery } from '../useImageGallery';
export { useContactPicker } from '../useContactPicker';
export { useFileSystem } from '../useFileSystem';
export { useIdleDetection } from '../useIdleDetection';
export { usePermission, usePermissions } from '../usePermissions';
export { useTextSelection } from '../useTextSelection';
export { useCountdown } from '../useCountdown';
export { useDebounce, useDebouncedCallback } from '../useDebounce';
export { useThrottle, useThrottledCallback } from '../useThrottle';
export { useDragAndDrop } from '../useDragAndDrop';
export { useSpeechSynthesis } from '../useSpeechSynthesis';
export { useAmbientLight } from '../useAmbientLight';
